services:
  - type: web
    name: ai-companion-api
    env: docker
    plan: starter
    region: oregon            # or frankfurt/singapore etc.
    autoDeploy: true
    healthCheckPath: /health
    dockerfilePath: api/Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false           # set in Render dashboard
      - key: POSTGRES_HOST
        fromService:
          type: pserv
          name: ai-companion-db
          property: host
      - key: POSTGRES_PORT
        value: 5432
      - key: POSTGRES_DB
        value: ai_companion
      - key: POSTGRES_USER
        value: dbuser
      - key: POSTGRES_PASSWORD
        sync: false           # set in Render dashboard
      - key: REDIS_URL
        fromService:
          type: redis
          name: ai-companion-redis
          property: connectionString

  - type: worker
    name: ai-companion-worker
    env: docker
    plan: starter
    region: oregon
    autoDeploy: true
    dockerfilePath: api/Dockerfile.worker
    envVars:
      - key: APP_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: POSTGRES_HOST
        fromService:
          type: pserv
          name: ai-companion-db
          property: host
      - key: POSTGRES_PORT
        value: 5432
      - key: POSTGRES_DB
        value: ai_companion
      - key: POSTGRES_USER
        value: dbuser
      - key: POSTGRES_PASSWORD
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: ai-companion-redis
          property: connectionString

  - type: redis
    name: ai-companion-redis
    plan: starter
    ipAllowList: []

databases:
  - name: ai-companion-db
    plan: starter
    databaseName: ai_companion
    user: dbuser
    ipAllowList: []           # private by default
