services:
  - type: web
    name: ai-companion-api
    env: docker
    plan: starter
    autoDeploy: true
    healthCheckPath: /health
    buildCommand: docker build -t ai-companion-api -f infra/Dockerfile.api .
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: APP_ENV
        value: production
      - key: POSTGRES_HOST
        fromService:
          type: pserv
          name: ai-companion-db
          property: host
      - key: POSTGRES_PORT
        value: 5432
      - key: POSTGRES_DB
        value: ai_companion
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: ai-companion-redis
          property: connectionString

  - type: worker
    name: ai-companion-worker
    env: docker
    autoDeploy: true
    buildCommand: docker build -t ai-companion-worker -f infra/Dockerfile.worker .
    startCommand: poetry run celery -A app.celery_app worker --loglevel=info
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: APP_ENV
        value: production
      - key: POSTGRES_HOST
        fromService:
          type: pserv
          name: ai-companion-db
          property: host
      - key: POSTGRES_PORT
        value: 5432
      - key: POSTGRES_DB
        value: ai_companion
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: ai-companion-redis
          property: connectionString

databases:
  - name: ai-companion-db
    plan: starter
    ipAllowList: []  # private
redis:
  - name: ai-companion-redis
    plan: starter
