services:
  - type: web
    name: ai-companion-api
    env: docker
    plan: starter
    region: oregon            # or frankfurt/singapore etc.
    autoDeploy: true
    healthCheckPath: /health
    dockerfilePath: api/Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false           # set in Render dashboard
      - key: APP_DATABASE__URL
        fromService:
          type: database
          name: ai-companion-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: ai-companion-redis
          property: connectionString

  - type: worker
    name: ai-companion-worker
    env: docker
    plan: starter
    region: oregon
    autoDeploy: true
    dockerfilePath: api/Dockerfile.worker
    envVars:
      - key: APP_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: APP_DATABASE__URL
        fromService:
          type: database
          name: ai-companion-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: ai-companion-redis
          property: connectionString

  - type: redis
    name: ai-companion-redis
    plan: starter
    ipAllowList: []

# Database managed outside the blueprint
